import style from "./ThanksMakdomCheck.module.scss";
import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
// react-qr-code
import QRCode from "react-qr-code";
// Material-UI
import { Button, Box, Typography } from "@mui/material";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import ErrorIcon from "@mui/icons-material/Error";
// import OpenInNewIcon from "@mui/icons-material/OpenInNew";
// Images
import imageA from "../../Assets/Images/A.png";
import imageB from "../../Assets/Images/B.png";
import imageC from "../../Assets/Images/C.png";
import imageD from "../../Assets/Images/D.png";
import WhatsAppLogo from "../../Assets/Images/WhatsApp_logo.png";
import AlAassamiTransport from "../../Assets/Images/albassamitransport.jpg";

export default function ThanksMakdomCheck() {
  useEffect(() => {
    // Scroll to the top of the page
    window.scrollTo(0, 0);
  }, []);
  // Get search params from current URL
  const searchParams = new URLSearchParams(window.location.search);
  // Get individual parameters
  // Moyasar params
  const status = searchParams.get("status");
  const message = searchParams.get("message");
  const id = searchParams.get("id");
  // Tamara params
  const tamaraPaymentStatus = searchParams.get("paymentStatus");
  const tamaraOrderId = searchParams.get("orderId"); // this is generated by tamara NOT me
  // Tabby params
  const tabbyPaymentId = searchParams.get("payment_id");
  const tabbyCancel = searchParams.get("cancel");
  const tabbyFail = searchParams.get("fail");
  const numOfParams = Array.from(new URLSearchParams(window.location.search).keys());

  const [paySuccess, setPaySuccess] = useState(false);
  const [isDownloaded, setIsDownloaded] = useState(false);

  useEffect(() => {
    if (status === "paid" && message === "APPROVED") {
      setPaySuccess(true);
    } else if (tamaraPaymentStatus === "approved" && tamaraOrderId) {
      setPaySuccess(true);
    } else if (tabbyPaymentId && tabbyCancel !== "true" && tabbyFail !== "true" && numOfParams.length === 1) {
      setPaySuccess(true);
    }
  }, [status, message, tamaraPaymentStatus, tamaraOrderId, tabbyPaymentId, tabbyCancel, tabbyFail, numOfParams]);

  const handleDownloadQRCode = () => {
    const svg = document.getElementById("qr-code-svg");
    const svgData = new XMLSerializer().serializeToString(svg);
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    const img = new Image();

    // Padding settings (in pixels)
    const padding = 20; // Adjust this value as needed

    img.onload = () => {
      // Set canvas size to include padding
      canvas.width = img.width + padding * 2;
      canvas.height = img.height + padding * 2;

      // Fill background with white
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Draw the QR code with padding
      ctx.drawImage(img, padding, padding, img.width, img.height);

      const pngFile = canvas.toDataURL("image/png");
      const downloadLink = document.createElement("a");
      downloadLink.download = `qrcode-${
        (id ? `moyasar-${id}` : "") || (tamaraOrderId ? `tamara-${tamaraOrderId}` : "") || (tabbyPaymentId ? `tabby-${tabbyPaymentId}` : "") || "ticket"
      }.png`;
      downloadLink.href = pngFile;
      downloadLink.click();
    };

    img.src = "data:image/svg+xml;base64," + btoa(svgData);
  };

  // Effect to automatically download QR code when component mounts and pay is successful
  useEffect(() => {
    if (paySuccess && !isDownloaded) {
      // Small delay to ensure QR code is rendered
      const timer = setTimeout(() => {
        handleDownloadQRCode();
        setIsDownloaded(true);
      }, 1500); // 1.5 second delay to ensure rendering

      return () => clearTimeout(timer);
    }
  }, [paySuccess, isDownloaded]);

  // Manual download handler
  const handleManualDownload = () => {
    handleDownloadQRCode();
  };

  // handleOpenWhatsApp
  const handleOpenWhatsApp = () => {
    const phoneNumber = "966548682102";
    // Open WhatsApp chat with the specific number
    const whatsappUrl = `https://wa.me/${phoneNumber}`;
    window.open(whatsappUrl, "_blank");
  };

  // handleOpenPricesPage
  const handleOpenPricesPage = () => {
    window.open(`${process.env.PUBLIC_URL}/prices-list`, "_blank");
  };

  // handleAskSippingService
  const handleAskSippingService = () => {
    window.open(`${process.env.PUBLIC_URL}/XXXXX`, "_blank");
  };

  return (
    <div className={style.container}>
      {paySuccess ? (
        <>
          {/* تم الدفع */}
          <div className={style.success_box}>
            <CheckCircleIcon sx={{ fontSize: 48, color: "#1fb952" }} />
            <h2>تم الدفع</h2>
            {/* <h4>اطلب من صاحب السيارة التوجه إلى الفرع المحدد، وإبراز الباركود التالي لموظف الاستقبال لإتمام إجراءات الفحص</h4> */}
          </div>

          {/* <Typography variant="h3" sx={{ mb: 1 }}>
            الخطوة اﻻولى
          </Typography> */}
          {/* <Typography variant="h5" sx={{ mb: 3, color: "rgb(211, 47, 47)" }}>
            (فحص السيارة)
          </Typography> */}

          {/* Steps Box */}
          <div dir="rtl" className={style.steps_box}>
            <Typography variant="h4" sx={{ mb: 1, textAlign: "center" }}>
              الخطوة اﻻولى
            </Typography>
            <Typography variant="h5" sx={{ mb: 3, color: "rgb(211, 47, 47)", textAlign: "center" }}>
              (فحص السيارة)
            </Typography>
            <ol
              style={{
                paddingRight: "18px",
              }}
            >
              <li>قم بتنزيل صورة الباركود وارسلها لصاحب السيارة.</li>
              <li>
                اطلب من صاحب السيارة التوجه الى{" "}
                <a href="https://cashif.cc/dashboard/contact" target="_blank">
                  الفرع المحدد
                </a>
                .
              </li>
              <li>بعد اﻻنتهاء من الفحص سيتم ارفاق تقرير الفحص عبر الواتساب وعبر الموقع اﻻلكتروني.</li>
            </ol>

            <Box display="flex" flexDirection="column" alignItems="center">
              <div style={{ background: "white", padding: "16px" }}>
                <QRCode id="qr-code-svg" value={id || (tamaraOrderId ? `tamara${tamaraOrderId}` : "") || (tabbyPaymentId ? `tabby${tabbyPaymentId}` : "")} size={250} level="H" />
              </div>
              <Button
                dir="rtl"
                variant="contained"
                onClick={handleManualDownload}
                className={style.download_btn}
                sx={{
                  padding: "8px 20px",
                  fontWeight: "bold",
                }}
              >
                تحميل الـ QR Code
              </Button>

              {/* Locations */}
              {/* <div style={{ marginBottom: "16px", marginTop: "16px", width: "100%" }}>
                <ul dir="rtl" className={style.locations_box}>
                  {[
                    { name: "الرياض-القادسية", url: "https://maps.app.goo.gl/MiFGsgakfo62on7u8" },
                    { name: "الرياض-الشفا", url: "https://maps.app.goo.gl/pXCnG7RPXJ2CDLqe7?g_st=aw" },
                    { name: "القصيم", url: "https://maps.app.goo.gl/Gd7g3VScomNQP8DR7" },
                    { name: "الدمام", url: "https://maps.app.goo.gl/9UiHq4kW7Mjh1Aik8" },
                    { name: "جدة", url: "https://maps.app.goo.gl/697yXkaS4o6kYsos8" },
                  ].map((location, index) => (
                    <li key={index}>
                      <Button
                        variant="text"
                        endIcon={<OpenInNewIcon sx={{ fontSize: "12px !important" }} />}
                        href={location.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        sx={{
                          textDecoration: "underline",
                          p: 0,
                          color: "#1976d2",
                          textTransform: "none",
                          fontWeight: "normal",
                          fontSize: "12px",
                          "& .MuiButton-endIcon": {
                            m: 0,
                            marginRight: "2px",
                          },
                          "&:hover": {
                            backgroundColor: "rgba(25, 118, 210, 0.04)",
                          },
                        }}
                      >
                        {location.name}
                      </Button>
                    </li>
                  ))}
                </ul>
              </div> */}
            </Box>
          </div>

          {/* Steps Box */}
          <div dir="rtl" className={style.steps_box}>
            <Typography variant="h4" sx={{ mb: 1, textAlign: "center" }}>
              الخطوة الثانية
            </Typography>
            <Typography variant="h5" sx={{ mb: 3, color: "rgb(211, 47, 47)", textAlign: "center" }}>
              (نقل الملكية والتأمين)
            </Typography>
            <ol
              style={{
                paddingRight: "18px",
              }}
            >
              <li>تواصل مع مسؤول النقل والتأمين في حال رغبت بنقل ملكية وتأمين السيارة.</li>
            </ol>

            <div style={{ width: "175px", margin: "auto" }}>
              <img style={{ width: "100%", padding: "16px" }} src={WhatsAppLogo} alt="WhatsApp Logo" />
            </div>

            <Button
              dir="rtl"
              variant="contained"
              onClick={handleOpenWhatsApp}
              className={style.download_btn}
              sx={{
                padding: "8px 20px",
                fontWeight: "bold",
              }}
            >
              اضغط هنا للمراسلة
            </Button>
          </div>

          {/* Steps Box */}
          <div dir="rtl" className={style.steps_box}>
            <Typography variant="h4" sx={{ mb: 1, textAlign: "center" }}>
              الخطوة الثالثة
            </Typography>
            <Typography variant="h5" sx={{ mb: 3, color: "rgb(211, 47, 47)", textAlign: "center" }}>
              (شحن السيارة)
            </Typography>
            <ol
              style={{
                paddingRight: "18px",
              }}
            >
              <li>مركز كاشف لا يستلم السيارة من صاحب السيارة.</li>
              <li>بعد إتمام الدفع عبر موقعنا الإلكتروني، يمكن لصاحب السيارة التوجه إلى شركة البسامي مباشرة.</li>
              <li>أو يمكنه الانتظار حتى وصول السطحة التابعة للبسامي لاستلام السيارة وشحنها إلى مدينتك.</li>
            </ol>

            <div style={{ width: "250px", margin: "auto" }}>
              <img style={{ width: "100%" }} src={AlAassamiTransport} alt="WhatsApp Logo" />
            </div>

            <Button
              dir="rtl"
              // variant="outlined"
              variant="contained"
              onClick={handleOpenPricesPage}
              // className={style.download_btn}
              sx={{
                padding: "8px 20px",
                fontWeight: "bold",
                width: "100%",
                // marginBottom: "16px",
              }}
            >
              التعرف على الأسعار
            </Button>

            {/* <Button
              dir="rtl"
              variant="contained"
              onClick={handleAskSippingService}
              className={style.download_btn}
              sx={{
                padding: "8px 20px",
                fontWeight: "bold",
              }}
            >
              اطلب الخدمة الآن
            </Button> */}
          </div>

          {/* Partner Coupon */}
          <div>
            {/* <Button
              variant="outlined"
              href="http://cashif.cc/"
              sx={{
                marginBottom: "40px",
                marginTop: "8px",
                borderColor: "#1976d2",
                color: "#1976d2",
                "&:hover": {
                  borderColor: "#115293",
                  backgroundColor: "rgba(25, 118, 210, 0.04)",
                },
              }}
            >
              عودة
            </Button> */}
            <div className={style.partner_container}>
              <h2 dir="rtl">
                خصم خاص <span>لعملاء كاشف!</span>
              </h2>
              <h4>اعرض الكوبونات لدى شركائنا عند وصولك</h4>
              <div className={style.partner_box}>
                {[
                  { image: imageA, name: "A" },
                  { image: imageB, name: "B" },
                  { image: imageC, name: "C" },
                  { image: imageD, name: "D" },
                ].map((partner, index) => (
                  <div key={index}>
                    <a href={partner.image} download={`coupon_${partner.name}.png`}>
                      <img src={partner.image} alt="our partner" />
                    </a>
                    <Button
                      variant="contained"
                      href={partner.image}
                      download=""
                      className={style[`btn_${["one", "two", "three", "four"][index]}`]}
                      sx={{
                        marginTop: 1,
                        textTransform: "none",
                        padding: "8px 16px",
                        fontWeight: "bold",
                      }}
                    >
                      تحميل الكوبون
                    </Button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </>
      ) : (
        <div className={style.error_box}>
          <ErrorIcon sx={{ fontSize: 48, color: "red" }} />

          <h2>خطأ في الدفع</h2>

          <Button
            component={Link}
            to={`${process.env.PUBLIC_URL}/prices`}
            variant="contained"
            sx={{
              marginTop: "16px",
              padding: "8px 20px",
              fontWeight: "bold",
            }}
          >
            عودة
          </Button>
        </div>
      )}
    </div>
  );
}
