import style from "./ThanksPurchaseCheck.module.scss";
import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
// react-qr-code
import QRCode from "react-qr-code";
// Material-UI
import { Button, Box } from "@mui/material";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import ErrorIcon from "@mui/icons-material/Error";
import LocationOnIcon from "@mui/icons-material/LocationOn";
import OpenInNewIcon from "@mui/icons-material/OpenInNew";
// Images
import imageA from "../../Assets/Images/A.png";
import imageB from "../../Assets/Images/B.png";
import imageC from "../../Assets/Images/C.png";
import imageD from "../../Assets/Images/D.png";

export default function ThanksPurchaseCheck() {
  useEffect(() => {
    // Scroll to the top of the page
    window.scrollTo(0, 0);
  }, []);
  // Get search params from current URL
  const searchParams = new URLSearchParams(window.location.search);
  // Get individual parameters
  // Moyasar params
  const status = searchParams.get("status");
  const message = searchParams.get("message");
  const id = searchParams.get("id");
  // Tamara params
  const tamaraPaymentStatus = searchParams.get("paymentStatus");
  const tamaraOrderId = searchParams.get("orderId"); // this is generated by tamara NOT me
  // Tabby params
  const tabbyPaymentId = searchParams.get("payment_id");
  const tabbyCancel = searchParams.get("cancel");
  const tabbyFail = searchParams.get("fail");
  const numOfParams = Array.from(new URLSearchParams(window.location.search).keys());

  const [paySuccess, setPaySuccess] = useState(false);
  const [isDownloaded, setIsDownloaded] = useState(false);

  useEffect(() => {
    if (status === "paid" && message === "APPROVED") {
      setPaySuccess(true);
    } else if (tamaraPaymentStatus === "approved" && tamaraOrderId) {
      setPaySuccess(true);
    } else if (tabbyPaymentId && tabbyCancel !== "true" && tabbyFail !== "true" && numOfParams.length === 1) {
      setPaySuccess(true);
    }
  }, [status, message, tamaraPaymentStatus, tamaraOrderId, tabbyPaymentId, tabbyCancel, tabbyFail, numOfParams]);

  const handleDownloadQRCode = () => {
    const svg = document.getElementById("qr-code-svg");
    const svgData = new XMLSerializer().serializeToString(svg);
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    const img = new Image();

    // Padding settings (in pixels)
    const padding = 20; // Adjust this value as needed

    img.onload = () => {
      // Set canvas size to include padding
      canvas.width = img.width + padding * 2;
      canvas.height = img.height + padding * 2;

      // Fill background with white
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Draw the QR code with padding
      ctx.drawImage(img, padding, padding, img.width, img.height);

      const pngFile = canvas.toDataURL("image/png");
      const downloadLink = document.createElement("a");
      downloadLink.download = `qrcode-${
        (id ? `moyasar-${id}` : "") || (tamaraOrderId ? `tamara-${tamaraOrderId}` : "") || (tabbyPaymentId ? `tabby-${tabbyPaymentId}` : "") || "ticket"
      }.png`;
      downloadLink.href = pngFile;
      downloadLink.click();
    };

    img.src = "data:image/svg+xml;base64," + btoa(svgData);
  };

  // Effect to automatically download QR code when component mounts and pay is successful
  useEffect(() => {
    if (paySuccess && !isDownloaded) {
      // Small delay to ensure QR code is rendered
      const timer = setTimeout(() => {
        handleDownloadQRCode();
        setIsDownloaded(true);
      }, 1500); // 1.5 second delay to ensure rendering

      return () => clearTimeout(timer);
    }
  }, [paySuccess, isDownloaded]);

  // Manual download handler
  const handleManualDownload = () => {
    handleDownloadQRCode();
  };

  return (
    <div className={style.container}>
      {paySuccess ? (
        <>
          <Box display="flex" flexDirection="column" alignItems="center" gap={2}>
            <div style={{ background: "white", padding: "16px" }}>
              <QRCode id="qr-code-svg" value={id || (tamaraOrderId ? `tamara${tamaraOrderId}` : "") || (tabbyPaymentId ? `tabby${tabbyPaymentId}` : "")} size={250} level="H" />
            </div>
            <Button
              dir="rtl"
              variant="contained"
              onClick={handleManualDownload}
              className={style.download_btn}
              sx={{
                padding: "8px 20px",
                fontWeight: "bold",
              }}
            >
              تحميل الـ QR Code
            </Button>
          </Box>

          <div className={style.success_box}>
            <CheckCircleIcon sx={{ fontSize: 48, color: "#1fb952" }} />

            <h2>تم الدفع</h2>
            <h4>قم بحفظ الباركود، لإبرازه لموظف الاستقبال في الفرع المحدد لإتمام إجراءات الفحص</h4>

            <Button
              variant="outlined"
              href="http://cashif.cc/"
              sx={{
                marginBottom: "40px",
                marginTop: "8px",
                borderColor: "#1976d2",
                color: "#1976d2",
                "&:hover": {
                  borderColor: "#115293",
                  backgroundColor: "rgba(25, 118, 210, 0.04)",
                },
              }}
            >
              عودة
            </Button>

            {/* Locations */}
            <ul dir="rtl" className={style.locations_box}>
              {[
                { name: "الرياض-القادسية", url: "https://maps.app.goo.gl/MiFGsgakfo62on7u8" },
                { name: "الرياض-الشفا", url: "https://maps.app.goo.gl/pXCnG7RPXJ2CDLqe7?g_st=aw" },
                { name: "الدمام", url: "https://maps.app.goo.gl/9UiHq4kW7Mjh1Aik8" },
                { name: "جدة", url: "https://maps.app.goo.gl/697yXkaS4o6kYsos8" },
              ].map((location, index) => (
                <li key={index}>
                  <Button
                    variant="text"
                    endIcon={<OpenInNewIcon sx={{ fontSize: "14px !important" }} />}
                    href={location.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    sx={{
                      textDecoration: "underline",
                      p: 0,
                      color: "#1976d2",
                      textTransform: "none",
                      fontWeight: "normal",
                      "& .MuiButton-endIcon": {
                        m: 0,
                        marginRight: "2px",
                      },
                      "&:hover": {
                        backgroundColor: "rgba(25, 118, 210, 0.04)",
                      },
                    }}
                  >
                    {location.name}
                  </Button>
                </li>
              ))}
            </ul>

            {/* Partner Coupon */}
            <div className={style.partner_container}>
              <h2 dir="rtl">
                خصم خاص <span>لعملاء كاشف!</span>
              </h2>
              <h4>اعرض الكوبونات لدى شركائنا عند وصولك</h4>
              <div className={style.partner_box}>
                {[
                  { image: imageA, name: "A" },
                  { image: imageB, name: "B" },
                  { image: imageC, name: "C" },
                  { image: imageD, name: "D" },
                ].map((partner, index) => (
                  <div key={index}>
                    <a href={partner.image} download={`coupon_${partner.name}.png`}>
                      <img src={partner.image} alt="our partner" />
                    </a>
                    <Button
                      variant="contained"
                      href={partner.image}
                      download=""
                      className={style[`btn_${["one", "two", "three", "four"][index]}`]}
                      sx={{
                        marginTop: 1,
                        textTransform: "none",
                        padding: "8px 16px",
                        fontWeight: "bold",
                      }}
                    >
                      تحميل الكوبون
                    </Button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </>
      ) : (
        <div className={style.error_box}>
          <ErrorIcon sx={{ fontSize: 48, color: "red" }} />

          <h2>خطأ في الدفع</h2>

          <Button
            component={Link}
            to={`${process.env.PUBLIC_URL}/prices`}
            variant="contained"
            sx={{
              marginTop: "16px",
              padding: "8px 20px",
              fontWeight: "bold",
            }}
          >
            عودة
          </Button>
        </div>
      )}
    </div>
  );
}
